"""add source_config to story_sources

Revision ID: 0d89c44caa71
Revises: e97e6b4b7495
Create Date: 2026-05-17 19:27:59.283340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d89c44caa71'
down_revision: Union[str, Sequence[str], None] = 'e97e6b4b7495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_sources', sa.Column('source_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False,server_default=sa.text(
            "'{}'::jsonb"
        )))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_sources', 'source_config')
    # ### end Alembic commands ###
