"""update lease_expires_at type

Revision ID: 278195a7a1f0
Revises: 72dbd7776335
Create Date: 2026-05-19 08:50:18.687906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278195a7a1f0'
down_revision: Union[str, Sequence[str], None] = '72dbd7776335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE tasks
        ALTER COLUMN lease_expires_at
        TYPE TIMESTAMP
        USING lease_expires_at::timestamp
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'lease_expires_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
