"""add workers table

Revision ID: 2ba12ee9b3f0
Revises: 34c91be41fb9
Create Date: 2026-05-21 22:49:03.744455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ba12ee9b3f0'
down_revision: Union[str, Sequence[str], None] = '34c91be41fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('worker_type', sa.String(), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('free_slots', sa.Integer(), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('is_charging', sa.Boolean(), nullable=True),
    sa.Column('tailscale_ip', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_worker_id'), 'workers', ['worker_id'], unique=True)
    op.create_index(op.f('ix_tasks_task_group'), 'tasks', ['task_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_group'), table_name='tasks')
    op.drop_index(op.f('ix_workers_worker_id'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
