"""add worker capabilities

Revision ID: 3ae90d7eccbf
Revises: a69a84349b77
Create Date: 2026-05-18 22:06:39.983169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ae90d7eccbf'
down_revision: Union[str, Sequence[str], None] = 'a69a84349b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('required_capabilities', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'required_capabilities')
    # ### end Alembic commands ###
