"""update channels table 1

Revision ID: 931d9056dd7f
Revises: ebfc49ad9f20
Create Date: 2026-05-23 16:10:59.856662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931d9056dd7f'
down_revision: Union[str, Sequence[str], None] = 'ebfc49ad9f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE channels
            ALTER COLUMN id
            SET DEFAULT gen_random_uuid();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'channel_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
