"""update website model

Revision ID: 9914830ff3ba
Revises: abe5548fef1a
Create Date: 2026-05-14 20:49:43.347726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9914830ff3ba'
down_revision: Union[str, Sequence[str], None] = 'abe5548fef1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('description', sa.String(), nullable=True))
    op.add_column('websites', sa.Column('parser_type', sa.String(), nullable=False))
    op.add_column('websites', sa.Column('render_engine', sa.String(), nullable=False))
    op.add_column('websites', sa.Column('enable_translate', sa.Boolean(), nullable=False))
    op.add_column('websites', sa.Column('use_proxy', sa.Boolean(), nullable=False))
    op.add_column('websites', sa.Column('rate_limit', sa.Integer(), nullable=False))
    op.add_column('websites', sa.Column('request_delay', sa.Integer(), nullable=False))
    op.add_column('websites', sa.Column('timeout', sa.Integer(), nullable=False))
    op.add_column('websites', sa.Column('retry_limit', sa.Integer(), nullable=False))
    op.add_column('websites', sa.Column('max_concurrency', sa.Integer(), nullable=False))
    op.add_column('websites', sa.Column('crawler_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'crawler_config')
    op.drop_column('websites', 'max_concurrency')
    op.drop_column('websites', 'retry_limit')
    op.drop_column('websites', 'timeout')
    op.drop_column('websites', 'request_delay')
    op.drop_column('websites', 'rate_limit')
    op.drop_column('websites', 'use_proxy')
    op.drop_column('websites', 'enable_translate')
    op.drop_column('websites', 'render_engine')
    op.drop_column('websites', 'parser_type')
    op.drop_column('websites', 'description')
    # ### end Alembic commands ###
