"""add unique chapter constraint

Revision ID: a69a84349b77
Revises: 05cde9d1909a
Create Date: 2026-05-18 21:28:50.439605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69a84349b77'
down_revision: Union[str, Sequence[str], None] = '05cde9d1909a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_story_source_chapter', 'chapters', ['story_source_id', 'chapter_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_story_source_chapter', 'chapters', type_='unique')
    # ### end Alembic commands ###
