"""add unique batch range

Revision ID: a9bac46655fc
Revises: 3ae90d7eccbf
Create Date: 2026-05-18 22:26:46.725026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bac46655fc'
down_revision: Union[str, Sequence[str], None] = '3ae90d7eccbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_story_batch_range', 'batches', ['story_id', 'start_chapter', 'end_chapter'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_story_batch_range', 'batches', type_='unique')
    # ### end Alembic commands ###
