"""add wait_for_task_types

Revision ID: b157afd8653b
Revises: f63d9b1a8135
Create Date: 2026-06-01 09:42:50.478934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b157afd8653b'
down_revision: Union[str, Sequence[str], None] = 'f63d9b1a8135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('wait_for_task_types', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'wait_for_task_types')
    # ### end Alembic commands ###
