"""create channels table

Revision ID: b59583db4f6a
Revises: d34076240afe
Create Date: 2026-05-23 15:43:26.830259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59583db4f6a'
down_revision: Union[str, Sequence[str], None] = 'd34076240afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(), nullable=False),
    sa.Column('mc_name', sa.String(), nullable=False),
    sa.Column('mc_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_channel_id')
    )
    op.add_column(
        'stories',
        sa.Column(
            'channel_id',
            sa.UUID(),
            nullable=True
        )
    )
    op.create_foreign_key(None, 'stories', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_column('stories', 'channel_id')
    op.drop_table('channels')
    # ### end Alembic commands ###
