"""update content domain model

Revision ID: bb1dd57a3b4a
Revises: 9914830ff3ba
Create Date: 2026-05-14 22:37:47.752633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1dd57a3b4a'
down_revision: Union[str, Sequence[str], None] = '9914830ff3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_ai_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('positive_prompt', sa.String(), nullable=True),
    sa.Column('negative_prompt', sa.String(), nullable=True),
    sa.Column('thumbnail_hook_template', sa.String(), nullable=True),
    sa.Column('narration_style', sa.String(), nullable=True),
    sa.Column('tts_voice', sa.String(), nullable=True),
    sa.Column('tts_model', sa.String(), nullable=True),
    sa.Column('image_style', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chapters', sa.Column('story_id', sa.UUID(), nullable=False))
    op.add_column('chapters', sa.Column('chapter_code', sa.String(), nullable=False))
    op.add_column('chapters', sa.Column('source_chapter_id', sa.String(), nullable=True))
    op.add_column('chapters', sa.Column('original_title', sa.String(), nullable=True))
    op.add_column('chapters', sa.Column('translated_title', sa.String(), nullable=True))
    op.add_column('chapters', sa.Column('translated_text', sa.String(), nullable=True))
    op.add_column('chapters', sa.Column('final_script', sa.String(), nullable=True))
    op.add_column('chapters', sa.Column('translation_status', sa.String(), nullable=False))
    op.add_column('chapters', sa.Column('tts_status', sa.String(), nullable=False))
    op.add_column('chapters', sa.Column('render_status', sa.String(), nullable=False))
    op.add_column('chapters', sa.Column('video_duration', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('published_at', sa.String(), nullable=True))
    op.alter_column('chapters', 'chapter_number',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('chapters', 'raw_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'chapters', 'stories', ['story_id'], ['id'])
    op.drop_column('chapters', 'title')
    op.add_column('stories', sa.Column('original_title', sa.String(), nullable=False))
    op.add_column('stories', sa.Column('ai_title', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('thumbnail_hook', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('background_image_url', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('default_ai_profile_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'stories', 'story_ai_profiles', ['default_ai_profile_id'], ['id'])
    op.drop_column('stories', 'author')
    op.drop_column('stories', 'title')
    op.add_column('story_sources', sa.Column('latest_chapter', sa.Integer(), nullable=False))
    op.add_column('story_sources', sa.Column('total_chapters', sa.Integer(), nullable=True))
    op.add_column('story_sources', sa.Column('crawl_status', sa.String(), nullable=False))
    op.add_column('story_sources', sa.Column('last_crawled_at', sa.String(), nullable=True))
    op.add_column('story_sources', sa.Column('last_chapter_crawled_at', sa.String(), nullable=True))
    op.add_column('story_sources', sa.Column('last_successful_crawl_at', sa.String(), nullable=True))
    op.add_column('story_sources', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_sources', 'is_active')
    op.drop_column('story_sources', 'last_successful_crawl_at')
    op.drop_column('story_sources', 'last_chapter_crawled_at')
    op.drop_column('story_sources', 'last_crawled_at')
    op.drop_column('story_sources', 'crawl_status')
    op.drop_column('story_sources', 'total_chapters')
    op.drop_column('story_sources', 'latest_chapter')
    op.add_column('stories', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stories', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_column('stories', 'default_ai_profile_id')
    op.drop_column('stories', 'background_image_url')
    op.drop_column('stories', 'thumbnail_hook')
    op.drop_column('stories', 'tags')
    op.drop_column('stories', 'genre')
    op.drop_column('stories', 'description')
    op.drop_column('stories', 'ai_title')
    op.drop_column('stories', 'original_title')
    op.add_column('chapters', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.alter_column('chapters', 'raw_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chapters', 'chapter_number',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('chapters', 'published_at')
    op.drop_column('chapters', 'video_duration')
    op.drop_column('chapters', 'render_status')
    op.drop_column('chapters', 'tts_status')
    op.drop_column('chapters', 'translation_status')
    op.drop_column('chapters', 'final_script')
    op.drop_column('chapters', 'translated_text')
    op.drop_column('chapters', 'translated_title')
    op.drop_column('chapters', 'original_title')
    op.drop_column('chapters', 'source_chapter_id')
    op.drop_column('chapters', 'chapter_code')
    op.drop_column('chapters', 'story_id')
    op.drop_table('story_ai_profiles')
    # ### end Alembic commands ###
