"""add task reservations

Revision ID: d34076240afe
Revises: 13294741ac81
Create Date: 2026-05-22 00:06:08.709087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd34076240afe'
down_revision: Union[str, Sequence[str], None] = '13294741ac81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_reservations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('task_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('lease_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_reservations_worker_id'), 'task_reservations', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_reservations_worker_id'), table_name='task_reservations')
    op.drop_table('task_reservations')
    # ### end Alembic commands ###
