"""redesign task schema

Revision ID: e48ed44cc38a
Revises: b6c585cb9583
Create Date: 2026-07-14 01:49:17.744723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e48ed44cc38a'
down_revision: Union[str, Sequence[str], None] = 'b6c585cb9583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=False),
    sa.Column('child_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['child_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_task_id', 'child_task_id', name='uq_task_dependency')
    )
    op.create_index('idx_dependency_child', 'task_dependencies', ['child_task_id'], unique=False)
    op.create_index('idx_dependency_parent', 'task_dependencies', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_child_task_id'), 'task_dependencies', ['child_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_parent_task_id'), 'task_dependencies', ['parent_task_id'], unique=False)
    op.add_column('tasks', sa.Column('remaining_dependencies', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'claimed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'lease_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'failed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_batch_chapter_id'), 'tasks', ['batch_chapter_id'], unique=False)
    op.create_index(op.f('ix_tasks_batch_id'), 'tasks', ['batch_id'], unique=False)
    op.create_index(op.f('ix_tasks_chapter_id'), 'tasks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_tasks_lease_expires_at'), 'tasks', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_worker_id'), 'tasks', ['worker_id'], unique=False)
    op.drop_constraint(op.f('tasks_depends_on_task_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'is_blocking')
    op.drop_column('tasks', 'depends_on_task_id')
    op.drop_column('tasks', 'claimed_by')
    op.drop_column('tasks', 'wait_for_task_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('wait_for_task_types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('claimed_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('depends_on_task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('is_blocking', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_depends_on_task_id_fkey'), 'tasks', 'tasks', ['depends_on_task_id'], ['id'])
    op.drop_index(op.f('ix_tasks_worker_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_lease_expires_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_chapter_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_batch_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_batch_chapter_id'), table_name='tasks')
    op.alter_column('tasks', 'failed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'lease_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'claimed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('tasks', 'remaining_dependencies')
    op.drop_index(op.f('ix_task_dependencies_parent_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_child_task_id'), table_name='task_dependencies')
    op.drop_index('idx_dependency_parent', table_name='task_dependencies')
    op.drop_index('idx_dependency_child', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
