"""add chapter_number to tasks

Revision ID: e76a09b72d7d
Revises: 278195a7a1f0
Create Date: 2026-05-19 17:35:31.531568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76a09b72d7d'
down_revision: Union[str, Sequence[str], None] = '278195a7a1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('chapter_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'chapter_number')
    # ### end Alembic commands ###
