"""update content domain model

Revision ID: ea3746a3703e
Revises: bb1dd57a3b4a
Create Date: 2026-05-14 22:55:35.342396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3746a3703e'
down_revision: Union[str, Sequence[str], None] = 'bb1dd57a3b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stories_default_ai_profile_id_fkey'), 'stories', type_='foreignkey')
    op.drop_column('stories', 'default_ai_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('default_ai_profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('stories_default_ai_profile_id_fkey'), 'stories', 'story_ai_profiles', ['default_ai_profile_id'], ['id'])
    # ### end Alembic commands ###
