"""update channels table

Revision ID: ebfc49ad9f20
Revises: b59583db4f6a
Create Date: 2026-05-23 16:02:58.145650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfc49ad9f20'
down_revision: Union[str, Sequence[str], None] = 'b59583db4f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('stories', 'channel_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('stories', 'channel_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # ### end Alembic commands ###
