"""update batch architecture

Revision ID: fe7c95aacfa0
Revises: d3c335344340
Create Date: 2026-05-18 21:24:49.642008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe7c95aacfa0'
down_revision: Union[str, Sequence[str], None] = 'd3c335344340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('story_source_id', sa.UUID(), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=False),
    sa.Column('start_chapter', sa.Integer(), nullable=False),
    sa.Column('end_chapter', sa.Integer(), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('completed_chapters', sa.Integer(), nullable=False),
    sa.Column('failed_chapters', sa.Integer(), nullable=False),
    sa.Column('manifest_path', sa.String(), nullable=True),
    sa.Column('output_dir', sa.String(), nullable=True),
    sa.Column('final_video_path', sa.String(), nullable=True),
    sa.Column('batch_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['story_source_id'], ['story_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_chapters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('chapter_video_path', sa.String(), nullable=True),
    sa.Column('subtitle_path', sa.String(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('manifest_path', sa.String(), nullable=True),
    sa.Column('render_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('batch_chapter_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('task_stage', sa.String(), nullable=False),
    sa.Column('task_group', sa.String(), nullable=True),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('manifest_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_chapter_id'], ['batch_chapters.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('batch_chapters')
    op.drop_table('batches')
    # ### end Alembic commands ###
